#!/python3


# By: Jankees Softwares
# Date: 14/09/21

#importando as libs
from pytube import YouTube, Playlist
import os

os.system("clear")
print("""
\033[1;36m
 _ __  _   _     _ __ ___   _____   _(_) ___
| '_ \| | | |   | '_ ` _ \ / _ \ \ / / |/ _ \*
| |_) | |_| |   | | | | | | (_) \ V /| |  __/
| .__/ \__, |___|_| |_| |_|\___/ \_/ |_|\___|
|_|    |___/_____|
By: Jankees Softwares
\033[0;0m
        """)
link = input("\033[1;31m[+]\033[1;36mLink do video:\033[0;0m ")
diretorio = input("\033[1;31m[+]\033[1;36mdiretotio para Download:\033[0;0m ")
yt = YouTube(link)

#informaçoes do video:
print("\033[1;36m[-]\033[0;0m\033[1;32mTitulo:\033[0;0m", yt.title)
print("\033[1;36m[-]\033[0;0m\033[1;32mNumero de views:\033[0;0m", yt.views)
print("\033[1;36m[-]\033[0;0m\033[1;32mAvaliação do video:\033[0;0m ", yt.rating)

print("\n\033[1;31m[-]\033[1;33mSelecione o tipo de Download!\033[0;0m\n\n\033[1;36m[1]\033[0;0m - \033[1;32mMusic '.mp3'\033[0;0m\n\033[1;36m[2]\033[0;0m - \033[1;32mVideo '.mp4'\033[0;0m\n\033[1;36m[3]\033[0;0m - \033[1;32mPlaylist\033[0;0m\n")

aux = input("\033[1;31m[+]\033[1;36mSua opção:\033[0;0m ")

if aux == "1":
    ys = yt.streams.get_by_itag(140)
    print("\033[1;31m[\]\033[1;34mBaixando...\033[0;0m")
    ys.download(diretorio)
    print("\033[1;31m[!!!]\033[1;33Download concluido!\033[0;0m")

elif aux == "2":
    print("\n\033[1;31m[+]\033[1;33mSelecione a qualidade de Download!\033[0;0m\n\n\033[1;36m[1]\033[0;0m - \033[1;32m360p\033[0;0m\n\033[1;36m[2]\033[0;0m - \033[1;32m720p\033[0;0m\n\033[1;36m[3]\033[0;0m - \033[1;32m1080p\033[0;0m\n")
    res = input("\033[1;31m[+]\033[1;36mSua opção:\033[0;0m ")

    if res == "1":
        ys = yt.streams.get_by_itag(18)
        print("\033[1;31m[\]\033[1;34mBaixando...\033[0;0m")
        ys.download(diretorio)
        print("\033[1;31m[!!!]\033[1;33mDownload concluido!\033[0;0m")

    elif res == "2":
        ys = yt.streams.get_by_itag(22)
        print("\033[1;31m[\]\033[0;0m\033[1;34mBaixando\033[0;0m")
        ys.download(diretorio)
        print("\033[1;31m[!!!]\033[0;0m\033[1;33mDownload concluido\033[0;0m")

    elif res == "3":
        ys = yt.streams.get_by_itag(137)
        print("\033[1;31m[\]\033[1;34mBaixando...\033[0;0m")
        ys.download(diretorio)
        print("\033[1;31m[!!!]\033[1;33mDownload concluido!\033[0;0m")
    else:
        print("\033[1;33m[!] Escolha nao existente!\033[0;0m")

elif aux == "3":
    p = Playlist(link)
    print(f"\033[1;31m[\]\033[1;36mBaixando: {p.title}\033[0;0m")
    for video in p.videos:
        video.streams.first().download()

else:
    print("\033[1;33m[!]Escolha nao existente!\033[0;0m")
